### ISSUE TITLE
Token not accepted by sqlite

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory#49] opened 2017-12-11 22:05 UTC
```docker run -p 80:80 -d --name bar -v /tmp/test/data:/scif/data expfactory/experiments --headless --experiments test-task,state-mindfulness-survey --no-randomize --database sqlite start```

```
root@efe66a7fe7ce:/scif/apps# expfactory users --list
/scif/data/expfactory/5a29fb1e-fd0c-453c-be90-cea6dc1cc765_finished	5a29fb1e-fd0c-453c-be90-cea6dc1cc765[finished]
/scif/data/expfactory/baf3dd04-587a-4cae-b859-7c0d48405cb0	baf3dd04-587a-4cae-b859-7c0d48405cb0[active]
```

Token `baf3dd04-587a-4cae-b859-7c0d48405cb0` rejected.

**Comment by vsoch** [comment] 2017-12-11 22:08
Could you make sure to delete the expfactory.db first before starting the application (just for sanity check)

**Comment by earcanal** [comment] 2017-12-11 22:09
I did that in the above test.  It was recreated (but empty).

**Comment by vsoch** [comment] 2017-12-11 22:11
okay I am rebuilding the image, and will test to reproduce the error! This is great, we are making sure all works. We probably should (after the next changes I will do to separate the builder) implement tests that ensure that all these functions (continue) to work.

**Comment by earcanal** [comment] 2017-12-11 22:15
Give all of the fancy, new options, it's already reached the point where test coverage is challenging.  I doubt that my tests covered more than 10% of the code.  I'm not sure what to use automate these tests as an initial regression suite, but it would definitely be a good idea!

It's ugly, as it needs a mixture of CLI and Selenium.

**Comment by vsoch** [comment] 2017-12-11 22:19
ok just reproduced!

**Comment by vsoch** [comment] 2017-12-11 22:20
That's a good point - should I add requirement of CI testing before merging this? It might be more sound than trying to add after, but it's such a small user base that it probably doesn't matter. I'd be ok to give this a go, at least. Let me debug this current one :)

**Comment by vsoch** [comment] 2017-12-11 22:32
This is a really cool bug, it's actually the case that the runtime database specification doesn't stand when you execute a (different) command to the running container. Here I am executing a command to just show the environment variable to determine the database:

```
$ docker exec -it  foo env | grep EXPFACTORY_DATABASE
EXPFACTORY_DATABASE=filesystem
```
and so when you execute the command to list users, you see the filesystem users (not the filesystem paths, we shouldn't see this with sqlite):

```
$ docker exec -it foo expfactory users --list 
/scif/data/expfactory/3eb83c14-ee01-4b38-a579-c927942732a8_finished	3eb83c14-ee01-4b38-a579-c927942732a8[finished]
/scif/data/expfactory/badbfba7-989d-453b-a0b3-9c24877ff763	badbfba7-989d-453b-a0b3-9c24877ff763[active]
```
and actually this is kosher - there isn't any reason that a container couldn't be used to serve multiple database types. Now look at what we see for the database setting when we use (docker) to set it:

```
$ docker exec -it --env EXPFACTORY_DATABASE=sqlite foo env | grep EXPFACTORY_DATABASE
EXPFACTORY_DATABASE=sqlite
```
and the corresponding command to list:

```
# no users
$ docker exec -it --env EXPFACTORY_DATABASE=sqlite foo expfactory users --list

# create new user
$ docker exec -it --env EXPFACTORY_DATABASE=sqlite foo expfactory users --new 1
DATABASE	TOKEN
1	d4a86c36-3261-4470-9877-af9b21afb749[active]

# list again
$ docker exec -it --env EXPFACTORY_DATABASE=sqlite foo expfactory users --list
1	d4a86c36-3261-4470-9877-af9b21afb749[active]
```
So the issue is that you are entering a filesystem token, which is not valid for sqlite. I need to think about how to manage this.

**Comment by vsoch** [comment] 2017-12-11 22:41
okay, I just fixed this, although it still requires user input. You can specify the database as an argument:

```
docker exec -it foo expfactory users --list --database sqlite
1	d4a86c36-3261-4470-9877-af9b21afb749[active]
```

**Comment by vsoch** [comment] 2017-12-11 22:45
I updated the docs to more specifically use this specification.

**Comment by vsoch** [comment] 2017-12-11 22:47
I'm going to close this issue, it was a UI bug!

**Closed as completed by vsoch** 2017-12-11 22:47 UTC
