### ISSUE TITLE
Single container containing experiments, surveys, (games)

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory#30] opened 2017-11-20 23:00 UTC
My current studies have a mixture of surveys and experiments.  Can you put different types of thing in the same container, or am I misunderstanding the pattern.

**Comment by vsoch** [comment] 2017-11-20 23:08
You can combine any experiments / surveys / games, they are all the same! The example containers on Docker Hub just happen to have them in groups, because why not :) If you have a list of experiments / surveys I can show you the commands to run.

**Comment by earcanal** [comment] 2017-11-20 23:15
Cool!

Breath counting, state mindfulness, attention network task, five facet mindfulness.  How do you specify the presentation order?

**Comment by vsoch** [comment] 2017-11-20 23:27
You would then want to run the builder with those experiments:

```
mkdir -p /tmp/mystudy
cd /tmp/mystudy
docker run vanessa/expfactory-builder -v $PWD:/data build breath-counting-task attention-network-task five-facet-mindfulness
```
After you do that there will be a Dockerfile and startscript.sh in the directory `/tmp/mystudy` and you can just build the image from it:

```
docker build -t earcanal/experiments .
```
Then when it's built run it with start:

```
docker run -p 80:80 earcanal/experiments start
```
If you don't have a Docker Hub account, you should make one! For example, my docker hub username is vanessa so if I make an image `vanessa/image` I can create a repository named `image` and then push the image to docker hub from my machine:

```
docker push vanessa/image
```
and then others can reproduce your experiment! 

I think the order would be random, but that's controlled by an environment variable specified at runtime. Let's get you done with the above steps then we can look at that.

**Comment by earcanal** [comment] 2017-12-02 11:35
/tmp/test$ docker run vanessa/expfactory-builder -v $PWD:/data build breath-counting-task attention-network-task five-facet-mindfulness test-task
    /tmp/test$ docker build -t earcanal/experiments .
    unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/test/Dockerfile: no such file or directory

**Comment by earcanal** [comment] 2017-12-02 12:21
These were just syntax issues.  The following works

    $ docker pull vanessa/expfactory-builder
    $ docker run -v $PWD:/data vanessa/expfactory-builder build breath-counting-task attention-network-task five-facet-mindfulness-survey test-task
    $ docker build -t earcanal/test .
    $ docker run -p 80:80 earcanal/test start

**Comment by vsoch** [comment] 2017-12-02 12:33
Yes you need the docker arguments before the image name. Feel free to close this if your issue is resolved.

**Closed as completed** 2017-12-02 12:50 UTC
