### ISSUE TITLE
Survey data JSON "flattened" when run in Docker container 

### ISSUE THREAD

**Issue by earcanal** [expfactory/expfactory#76] opened 2018-03-22 08:22 UTC
## Version of Experiment Factory:

3.1.0

### Expected behavior

JSON which is easily deserialised (i.e. the form generated when running a survey locally).

### Actual behavior

"Flat" JSON which is hard to deserialise.

### Steps to reproduce behavior

To generate expected data:

1. https://expfactory-experiments.github.io/state-mindfulness-survey/
1. Download

To generate "flat" data:

1. `docker run -p 80:80 vanessa/expfactory-surveys start`
1. Complete state-mindfulness-survey
1. `docker cp $container_id:/scif/data/expfactory/00000/state-mindfulness-survey-results.json .`

[issue6.zip](https://github.com/expfactory/expfactory/files/1836640/issue6.zip)

**Comment by vsoch** [comment] 2018-03-22 14:06
okay, confirmed that results in the browser (Github) are the same as the experiment container, and this means it's the internal parsing.

![image](https://user-images.githubusercontent.com/814322/37775200-b50fa2aa-2db8-11e8-8b52-1f00bbb1631d.png)

Going to peek inside now.

**Comment by vsoch** [comment] 2018-03-22 14:18
okay I think there is one level of data too many! Try the same experiment built into a container, and in the index.html instead of this:

```

type: 'POST',
--
  | url: '/save',
  | data: {'data': results},

```
Just try for this:

```

type: 'POST',
--
  | url: '/save',
  | data: results,
```

**Comment by earcanal** [comment] 2018-03-22 14:54
That breaks the survey :(  I've pushed that change to https://github.com/earcanal/state-mindfulness-survey-2, so you can see for yourself (without building a container) by cloning, then opening `index.html` in a browser.

**Comment by vsoch** [comment] 2018-03-22 14:56
Can you just turn on Github pages? It will deploy at https://earcanal.github.io/state-mindfulness-survey-2

**Comment by vsoch** [comment] 2018-03-22 14:58
I can just look at the html, you didn't change it like above, you did:

```
    url: '/save',
                data: 'data': results,
```
:)

**Comment by earcanal** [comment] 2018-03-22 15:28
Oops, sorry.  Fixed both of those things.  Still a diff between local and remote (containerized) data files.

[issue6-1.zip](https://github.com/expfactory/expfactory/files/1838174/issue6-1.zip)

**Comment by vsoch** [comment] 2018-03-22 23:43
okay still debugging! I think it has to do with what happens when the data is posted. That exact structure goes into the POST, then is represented in the request.form, and then looks like this:

```
dict_keys(['data[2][options]', 'data[12][value]', 'data[7][name]', 'data[14][value]', 'data[7][text]', 'data[6][name]', 'data[8][name]', 'data[4][text]', 'data[20][options]', 'data[15][options]', 'data[2][text]', 'data[6][text]', 'data[10][value]', 'data[13][value]', 'data[18][name]', 'data[17][options]', 'data[2][name]', 'data[7][options]', 'data[18][text]', 'data[12][text]', 'data[0][value]', 'data[19][options]', 'data[7][value]', 'data[18][value]', 'data[19][name]', 'data[10][text]', 'data[11][text]', 'data[14][options]', 'data[10][options]', 'data[3][options]', 'data[12][name]', 'data[11][options]', 'data[8][value]', 'data[1][options]', 'data[6][value]', 'data[5][text]', 'data[9][text]', 'data[4][value]', 'data[14][text]', 'data[16][value]', 'data[0][name]', 'data[3][text]', 'data[20][text]', 'data[6][options]', 'data[4][name]', 'data[18][options]', 'data[11][name]', 'data[11][value]', 'data[13][options]', 'data[15][name]', 'data[20][name]', 'data[8][options]', 'data[16][text]', 'data[16][options]', 'data[13][text]', 'data[15][value]', 'data[12][options]', 'data[4][options]', 'data[8][text]', 'data[0][options]', 'data[16][name]', 'data[17][text]', 'data[10][name]', 'data[17][value]', 'data[9][value]', 'data[3][name]', 'data[5][options]', 'data[17][name]', 'data[20][value]', 'data[1][text]', 'data[2][value]', 'data[3][value]', 'data[1][value]', 'data[13][name]', 'data[5][value]', 'data[9][options]', 'data[1][name]', 'data[19][text]', 'data[5][name]', 'data[9][name]', 'data[14][name]', 'data[19][value]', 'data[15][text]', 'data[0][text]'])
```
In fact it's a MultiDict generator:

```
ewhat| Well| Very well')]
>>> data.items()
<generator object MultiDict.items at 0x7f0157ff31a8>
```
And so the way we parse it, by json dumping that object, technically results in what we would expect. So it's not that any weird parsing is going on, it's something about how the data comes into flask in the request.form. Read here --> https://stackoverflow.com/questions/10434599/how-to-get-data-received-in-flask-request it is expecting and requiring key/value pairs, and so if you dump something that isn't that, the result is a "squished" or flattened version.

So what we need to do is try parsing the request.data, and importantly, making sure that it doesn't break the other experiments. I'll do a fix with a different builder and ping you when it's done, and then we can test it out.

**Comment by vsoch** [comment] 2018-03-23 08:12
okay next fixes to try! It looks like we should specify the data type of the request, see here:

https://stackoverflow.com/questions/34909916/datatables-flattens-json-data-on-posting-how-to-decode-into-python-dictionary/34912661

But actually I want to try using a more preferred method, fetch first. See "posting form data" here:

https://davidwalsh.name/fetch

Could we try to change the version 2 experiment that you made to use fetch? If that doesn't work, then we will try specifying the response type to be json instead, like:

```
type: 'POST',
url: '/save',
data: results,
dataType: "json",
contentType: "application/json;charset=utf-8"
```
BUT I think we want fetch instead. If fetch is preferred I'll have to go through and fix all the 50+ surveys, ahhhh.

**Comment by earcanal** [comment] 2018-03-23 10:45
Fork it and PR?

**Comment by vsoch** [comment] 2018-03-23 15:10
For this one https://earcanal.github.io/state-mindfulness-survey-2
it's your repo so I think you can just push to it :) I'm around now so will be able to test. We can try the fetch first, then the second option!

**Comment by earcanal** [comment] 2018-03-24 20:38
I had a read of the `fetch` approach but my js is too rusty to understand how to implement it right now!  Need to get back to data analysis for a while, so I'll take another look if this is still open when I get some more time.

**Comment by vsoch** [comment] 2018-06-26 17:58
We have provided examples now for how to load the data (it's just json wrapped in json because the experiment serialized to json, and it could equivalently be some other text) so I'm going to close this issue.

**Closed as completed by vsoch** 2018-06-26 17:58 UTC

**Comment by earcanal** [comment] 2018-06-26 20:09
Could you link to the examples?

**Comment by vsoch** [comment] 2018-06-26 20:22
Yep! The verbose description is here --> https://expfactory.github.io/expfactory/usage#working-with-json
which links to python and R examples here --> https://gist.github.com/vsoch/76d8933e3ff7e080883362b8baa4a164
In the first it says python only, I'll fix that so it mentions there is an R included at the bottom of the gist as well.

**Comment by earcanal** [comment] 2018-08-16 18:02
I suspect that gist only handles the double JSON encoding for *experiments* (not surveys).  Code to parse double encoded surveys (and experiments) is in https://github.com/earcanal/expfactoryr/blob/master/R/expfactoryr.R.

**Comment by vsoch** [comment] 2018-08-16 18:04
Thanks! If you want to PR to add this note / link to docs, would be appreciated!
